#cloud-config

package_update: true
package_upgrade: true
packages:
  - dialog
  - fail2ban
  - python3-venv
  - python3-dev
  - default-libmysqlclient-dev
  - build-essential
  - pkg-config
  - libapache2-mod-wsgi-py3

runcmd:
  # Enable fail2ban
  - printf "[sshd]\nenabled = true\nbanaction = iptables-multiport" > /etc/fail2ban/jail.local
  - systemctl enable fail2ban
  # Create mysql user and database
  - . /root/.hcloud_password
  - mysql_showreel_pass="$(tr -dc A-Za-z0-9 </dev/urandom | head -c 48)"
  - printf "mysql_showreel_pass=\"${mysql_showreel_pass}\"\n" >> /root/.hcloud_password
  - mysql --user="root" --password="${mysql_root_pass}" --execute="CREATE USER 'showreel'@'localhost' IDENTIFIED BY '${mysql_showreel_pass}';"
  - mysql --user="root" --password="${mysql_root_pass}" --execute="CREATE DATABASE showreel;"
  - mysql --user="root" --password="${mysql_root_pass}" --execute="GRANT ALL ON showreel.* TO 'showreel'@'localhost'"
  # Enable apache wsgi module
  - a2enmod wsgi
  # Create guided setup script
  - curl https://raw.githubusercontent.com/godotengine/godot-showreel-voting/master/deployment/guided_setup.sh -o /usr/local/sbin/showreel-guided-setup
  - chmod +x /usr/local/sbin/showreel-guided-setup
  # Perform a clean boot with the new configuations
  - reboot
